Repository step-Mate/Android, pull requests merged in 2024-03, with the labels that each got.

#27 fix : 랭킹 친구 신청 알림 표시 추가
  feature/ranking/src/main/kotlin/jinproject/stepwalk/ranking/rank/RankingScreen.kt
  feature/ranking/src/main/kotlin/jinproject/stepwalk/ranking/rank/RankingViewModel.kt
  feature/ranking/src/main/kotlin/jinproject/stepwalk/ranking/rank/component/RankingTopBar.kt
Labels: feature, design

#28 내 정보 화면 수정
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/NavigationGraph.kt
  design/src/main/kotlin/jinproject/stepwalk/design/component/WebView.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/navigation/ProfileNavigation.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/profile/component/ProfileDetail.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/profile/component/ProfileDialog.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/terms/component/TermsWebView.kt
Labels: hot fix

#29 fix : 홈화면 핫픽스
  app/src/main/kotlin/jinproject/stepwalk/app/StepMateActivity.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/NetworkState.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/StepMateViewModel.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/NavigationGraph.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/permission/PermissionRequester.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/permission/PermissionScreen.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/permission/PermissionViewModel.kt
  data/src/main/kotlin/jinproject/stepwalk/data/di/Retrofit.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/HealthConnector.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/HomeScreen.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/HomeViewModel.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/component/userinfo/UserInfoLayout.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/service/StepSensorViewModel.kt
Labels: hot fix, design

#31 feat : 신체 정보 입력 화면 구현
  app/src/main/kotlin/jinproject/stepwalk/app/StepMateActivity.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/StepMateViewModel.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/NavigationGraph.kt
  app/src/main/kotlin/jinproject/stepwalk/app/ui/navigation/permission/PermissionScreen.kt
  data/src/main/kotlin/jinproject/stepwalk/data/repositoryImpl/UserRepositoryImpl.kt
  design/src/main/kotlin/jinproject/stepwalk/design/component/NumberPicker.kt
  design/src/main/kotlin/jinproject/stepwalk/design/component/TopBar.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/Sample.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/repository/UserRepository.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/usecase/user/SetBodyLocalUseCases.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/homeSetting/HomeSettingScreen.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/homeUserBody/HomeUserBodyScreen.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/homeUserBody/HomeUserBodyViewModel.kt
Labels: feature

#33 feat : 유저 캐릭터 추가
  app/src/main/assets/ch_avocado.json
  app/src/main/assets/ch_broccoli.json
  app/src/main/assets/ch_caterpillars.json
  app/src/main/assets/ch_coffee.json
  app/src/main/assets/ch_donut.json
  app/src/main/assets/ch_fat_bird.json
  app/src/main/assets/ch_fox.json
  app/src/main/assets/ch_french_fries.json
  app/src/main/assets/ch_orange.json
  app/src/main/assets/ch_plant.json
  app/src/main/assets/ch_sandwich.json
  app/src/main/assets/ch_watermelon.json
  app/src/main/kotlin/jinproject/stepwalk/app/StepMateActivity.kt
  feature/core/src/main/kotlin/jinproject/stepwalk/core/Character.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/calendar/CalendarScreen.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/calendar/CalendarViewModel.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/HomeScreen.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/HomeUiStatePreviewParameters.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/HomeViewModel.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/component/tab/HealthTabLayout.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/component/tab/menu/MenuPager.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/component/userinfo/UserInfoLayout.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/state/Menu.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/state/Step.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/screen/home/state/User.kt
  feature/ranking/src/main/kotlin/jinproject/stepwalk/ranking/rank/RankingScreen.kt
Labels: feature

#32 미션 화면 핫픽스
  data/src/main/kotlin/jinproject/stepwalk/data/local/database/dao/MissionLocal.kt
  data/src/main/kotlin/jinproject/stepwalk/data/remote/api/MissionApi.kt
  data/src/main/kotlin/jinproject/stepwalk/data/remote/dto/response/mission/MissionResponse.kt
  data/src/main/kotlin/jinproject/stepwalk/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/kotlin/jinproject/stepwalk/data/repositoryImpl/MissionRepositoryImpl.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/repository/MissionRepository.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/usecase/mission/GetAllMissionListUseCases.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/usecase/mission/GetMissionListUseCases.kt
  domain/src/main/kotlin/jinproject/stepwalk/domain/usecase/mission/UpdateMissionUseCases.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/service/StepSensorViewModel.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/service/StepService.kt
  feature/home/src/main/kotlin/jinproject/stepwalk/home/worker/MissionUpdateWorker.kt
  feature/login/src/main/kotlin/jinproject/stepwalk/login/screen/component/LoginLayout.kt
  feature/login/src/main/kotlin/jinproject/stepwalk/login/screen/information/InformationScreen.kt
  feature/login/src/main/kotlin/jinproject/stepwalk/login/screen/signup/SignUpScreen.kt
  feature/login/src/main/kotlin/jinproject/stepwalk/login/screen/signupdetail/SignUpDetailScreen.kt
  feature/mission/src/main/kotlin/jinproject/stepwalk/mission/screen/component/MissionView.kt
  feature/mission/src/main/kotlin/jinproject/stepwalk/mission/screen/mission/MissionScreen.kt
  feature/mission/src/main/kotlin/jinproject/stepwalk/mission/screen/mission/component/MissionItem.kt
  feature/mission/src/main/kotlin/jinproject/stepwalk/mission/screen/missiondetail/MissionDetailScreen.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/edit/EditScreen.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/edit/EditViewModel.kt
  feature/profile/src/main/kotlin/jinproject/stepwalk/profile/screen/profile/ProfileViewModel.kt
Labels: hot fix

#35 내 정보 화면 수정
  feature/profile/src/main/kotlin/com/stepmate/profile/screen/profile/ProfileViewModel.kt
  feature/profile/src/main/kotlin/com/stepmate/profile/screen/profile/component/ProfileDetail.kt
Labels: design

#36 로그인 화면 수정
  feature/login/src/main/kotlin/com/stepmate/login/screen/component/LoginTextField.kt
Labels: design

#37 fix : 신체정보 입력 화면 수정
  feature/home/src/main/kotlin/com/stepmate/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/stepmate/home/screen/homeUserBody/HomeUserBodyScreen.kt
  feature/home/src/main/kotlin/com/stepmate/home/screen/homeUserBody/HomeUserBodyViewModel.kt
Labels: design

#38 미션 화면 핫픽스
  data/src/main/kotlin/com/stepmate/data/repositoryImpl/MissionRepositoryImpl.kt
  domain/src/main/kotlin/com/stepmate/domain/repository/MissionRepository.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/CompleteMissionUseCases.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/UpdateMissionListUseCases.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepService.kt
  feature/mission/src/main/kotlin/com/stepmate/mission/screen/mission/MissionScreen.kt
  feature/mission/src/main/kotlin/com/stepmate/mission/screen/mission/MissionViewModel.kt
  feature/mission/src/main/kotlin/com/stepmate/mission/util/NotificationHandler.kt
  feature/profile/src/main/kotlin/com/stepmate/profile/screen/edit/EditViewModel.kt
Labels: hot fix

#40 미션 핫픽스
  data/src/main/kotlin/com/stepmate/data/local/database/dao/MissionLocal.kt
  data/src/main/kotlin/com/stepmate/data/remote/dto/response/mission/MissionResponse.kt
  data/src/main/kotlin/com/stepmate/data/repositoryImpl/MissionRepositoryImpl.kt
  domain/src/main/kotlin/com/stepmate/domain/model/mission/MissionComposite.kt
  domain/src/main/kotlin/com/stepmate/domain/repository/MissionRepository.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/GetAllMissionListUseCases.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/GetMissionAchievedUseCases.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/GetMissionListUseCases.kt
  domain/src/main/kotlin/com/stepmate/domain/usecase/mission/ResetMissionTimeUseCases.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepSensorViewModel.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepService.kt
  feature/mission/src/main/kotlin/com/stepmate/mission/screen/component/MissionView.kt
  feature/mission/src/main/kotlin/com/stepmate/mission/screen/missiondetail/component/MissionDetailView.kt
  feature/profile/src/main/kotlin/com/stepmate/profile/screen/profile/ProfileViewModel.kt
Labels: hot fix

#41 fix : 걸음수 수집 예외처리
  app/src/main/kotlin/com/stepmate/app/StepMateActivity.kt
  app/src/main/kotlin/com/stepmate/app/ui/StepMateViewModel.kt
  feature/home/src/main/kotlin/com/stepmate/home/screen/calendar/CalendarViewModel.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepSensorViewModel.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepService.kt
Labels: hot fix

#42 fix : 걸음수 수집 로직 수정
  domain/src/main/kotlin/com/stepmate/domain/model/StepData.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepSensorViewModel.kt
  feature/home/src/main/kotlin/com/stepmate/home/service/StepService.kt
Labels: hot fix
